
include ./kitty-themes/themes/Monokai.conf

# FONT
font_family      MesloLGS NF Regular
bold_font        MesloLGS NF Bold
italic_font      MesloLGS NF Italic
bold_italic_font MesloLGS NF Bold Italic

font_size 16.0

# color0 #26282c
# color1 #ff615c
# color2 #70c43f
# color3 #d0b343
# color4 #4878bc
# color5 #98719f
# color6 #67a0b2
# color7 #c5c8c6
#
# color8  #9a9a99
# color9  #fe2626
# color10 #00813c
# color11 #d08341
# color12 #1984e9
# color13 #fe2c79
# color14 #398280
# color15 #fdfdc5
background #252525
foreground #d4d7d5

background_opacity 0.9

window_padding_width 10
hide_window_decorations no

# CURSOR
shell_integration no-cursor
cursor_shape block
cursor #cccccc
cursor_blink_interval      0.5
cursor_stop_blinking_after 15.0
mouse_hide_wait 3.0
clear_all_mouse_actions no
scrollback_lines 10000

kitty_mod cmd

# WINDOW
draw_minimal_borders no
hide_window_decorations yes
macos_option_as_alt yes
macos_quit_when_last_window_closed yes
confirm_os_window_close 0

# EOF
