# [theme]
# theme = "gruvbox-dark"

[icons]
icons = "awesome4"

[[block]]
block = "load"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:15,rot_interval:0.5) |}"
format_alt = " $icon $prev {$title.str(max_w:15,rot_interval:0.5) $play $next |}"

[[block]]
block = "temperature"
format = " $icon $max "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "

[[block]]
block = "sound"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid |Wired connection}"

[[block]]
block = "external_ip"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "time"

[[block]]
block = "battery"

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |}"
driver = "swaync"

[[block.click]]
button = "left"
action = "show"

[[block.click]]
button = "right"
action = "toggle_paused"
