# https://github.com/cdunku/dotfiles/blob/2b0775380402c36e7beef46850b982a10901f1df/alacritty/gruber_darker.yml
[colors.primary]
background = '#181818'
foreground = '#e4e4ef'

[colors.normal]
black =   '#000000'
red =     '#f43841'
green =   '#73c936'
yellow =  '#ffdd33'
blue =    '#5f627f'
magenta = '#9e95c7'
cyan =    '#5f627f'
white =   '#ffffff'

[colors.bright]
black =   '#282828'
red =     '#ff4f58'
green =   '#73c936'
yellow =  '#ffdd33'
blue =    '#96a6c8'
magenta = '#9e95c7'
cyan =    '#96a6c8'
white =   '#ffffff'

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x1d2021"
