# https://github.com/jonhoo/configs/blob/623f560d5bc5f861188289920fb431a3cf4d4e11/gui/.config/alacritty/alacritty.toml

[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

[colors.normal]
black = "0x1d2021"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xd5c4a1"
yellow = "0xfabd2f"

[colors.bright]
black = "0x665c54"
blue = "0xbdae93"
cyan = "0xd65d0e"
green = "0x3c3836"
magenta = "0xebdbb2"
red = "0xfe8019"
white = "0xfbf1c7"
yellow = "0x504945"

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x1d2021"
