# https://github.com/lysyi3m/macos-terminal-themes/blob/d0de673d9eaf2a756a0f383a6f09fec48c669a0a/themes/Homebrew.terminal

[colors.primary]
background = '#000000'
foreground = '#00FF00'


[colors.cursor]
text = '#000000'
cursor = '#23FF17'

[colors.selection]
text = '#00FF00'
background = '#08392A'

[colors.normal]
black   = '#000000'
red     = '#990000'
green   = '#00A652'
yellow  = '#999900'
blue    = '#0000B3'
magenta = '#B30085'
cyan    = '#00B3B3'
white   = '#BFBFBF'

[colors.bright]
black   = '#666666'
red     = '#E50000'
green   = '#00D900'
yellow  = '#E5E500'
blue    = '#0000FF'
magenta = '#E500E5'
cyan    = '#00E5E5'
white   = '#E5E5E5'
