import = [
  "~/.config/alacritty/themes/monokai.toml"
]

[font]
size = 14
normal = { family = "Hack Nerd Font" }

[keyboard]
bindings = [ { key = "F", mods = "Alt", action = "ToggleSimpleFullscreen" }, ]

[window]
option_as_alt = "OnlyLeft" # | "OnlyRight" | "Both" | "None" # (macos only)
startup_mode = "Maximized" # | "Fullscreen" | "SimpleFullscreen"
padding = { x = 20, y = 30 }
decorations = "transparent"
opacity = 0.9
blur = true
