[general]
import = [
"themes/jonhoo.toml"
# "themes/batlong.toml"
]

[window]
decorations = "none"
# opacity = 0.95

[scrolling]
history = 0

[font]
size = 12

[font.normal]
family="JetBrainsMono Nerd Font"

[bell]
animation = "EaseOut"
duration = 300
color = "#181800"

[selection]
save_to_clipboard = true

[terminal]
shell = "my_tmux.fish"
 
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"
