theme = "dracula"

[editor]
mouse = false
line-number = "relative"
color-modes = true
text-width = 80

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = "│"
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding", "file-line-ending"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[keys.normal]
Z = { Q = ":quit!", Z = ":x" }

[keys.insert]
"C-[" = "normal_mode"
