[language-server]
clangd = { command = "clangd", args = [ "--clang-tidy" ] }

[language-server.rust-analyzer.config]
check = {command = "clippy", extraArgs = ["--", "-W", "clippy::unwrap_used", "-W", "clippy::expect_used", "-W", "clippy::pedantic", "-W", "clippy::nursery"]}

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "rust"
formatter = { command = "rustfmt" }

[[language]]
name = "julia"
# formatter = { command = "julia", timeout = 60, args = [ "-e", "using JuliaFormatter; println(\"Hello\", length(ARGS)); format(ARGS[1]);", ] }
# args = [ "--project=@LanguageServer", "--startup-file=no", "--history-file=no", "-e", "using LanguageServer; runserver()" ]

[[language]]
name = "python"
formatter = { command = "ruff --format" }
# auto-format = true
