[language-server]
clangd = { command = "clangd", args = [ "--clang-tidy" ] }

[[language]]
name = "c"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "cpp"
auto-format = true
formatter = { command = "clang-format" }

[[language]]
name = "rust"
formatter = { command = "rustfmt" }

[[language]]
name = "julia"
auto-format = true
# formatter
